export const CREATE_WITHDRAWAL_REQUEST = "CREATE_WITHDRAWAL_REQUEST";
export const CREATE_WITHDRAWAL_SUCCESS = "CREATE_WITHDRAWAL_SUCCESS";
export const CREATE_WITHDRAWAL_FAILURE = "CREATE_WITHDRAWAL_FAILURE";

export const GET_WITHDRAWALS_REQUEST = "GET_WITHDRAWALS_REQUEST";
export const GET_WITHDRAWALS_SUCCESS = "GET_WITHDRAWALS_SUCCESS";
export const GET_WITHDRAWALS_FAILURE = "GET_WITHDRAWALS_FAILURE";

export const GET_ALL_WITHDRAWALS_SUCCESS = "GET_ALL_WITHDRAWALS_SUCCESS";
export const GET_ALL_WITHDRAWALS_FAILURE = "GET_ALL_WITHDRAWALS_FAILURE";

export const PROCEED_WITHDRAWAL_SUCCESS = "PROCEED_WITHDRAWAL_SUCCESS";
export const PROCEED_WITHDRAWAL_FAILURE = "PROCEED_WITHDRAWAL_FAILURE";
