export const ADD_PAYMENT_DETAILS_REQUEST = 'ADD_PAYMENT_DETAILS_REQUEST';
export const ADD_PAYMENT_DETAILS_SUCCESS = 'ADD_PAYMENT_DETAILS_SUCCESS';
export const ADD_PAYMENT_DETAILS_FAILURE = 'ADD_PAYMENT_DETAILS_FAILURE';

export const GET_PAYMENT_DETAILS_REQUEST = 'GET_PAYMENT_DETAILS_REQUEST';
export const GET_PAYMENT_DETAILS_SUCCESS = 'GET_PAYMENT_DETAILS_SUCCESS';
export const GET_PAYMENT_DETAILS_FAILURE = 'GET_PAYMENT_DETAILS_FAILURE';
