export const FETCH_ASSETS_REQUEST = 'FETCH_ASSETS_REQUEST';
export const FETCH_ASSETS_SUCCESS = 'FETCH_ASSETS_SUCCESS';
export const FETCH_ASSETS_FAILURE = 'FETCH_ASSETS_FAILURE';

export const GET_HOLDING_SUCCESS = 'GET_HOLDING_SUCCESS';
export const GET_HOLDING_FAILURE = 'GET_HOLDING_FAILURE';
export const GET_HOLDING_REQUEST = 'GET_HOLDING_REQUEST';


