export const FETCH_WATCHLIST_REQUEST = "FETCH_WATCHLIST_REQUEST";
export const FETCH_WATCHLIST_SUCCESS = "FETCH_WATCHLIST_SUCCESS";
export const FETCH_WATCHLIST_FAILURE = "FETCH_WATCHLIST_FAILURE";

export const TOGGLE_WATCHLIST_ITEM_REQUEST = "TOGGLE_WATCHLIST_ITEM_REQUEST";
export const TOGGLE_WATCHLIST_ITEM_SUCCESS = "TOGGLE_WATCHLIST_ITEM_SUCCESS";
export const TOGGLE_WATCHLIST_ITEM_FAILURE = "TOGGLE_WATCHLIST_ITEM_FAILURE";
